const restaurant_list = [
    {
        id: 1,
        image: '/images/katinat.jpg',
        title: 'Katinat Xuan Thuy',
        address: 'Thao Dien, Q2',
        rating: '4.5 stars',
        description: 'Slow-cooked for eight hours, this intensely flavored and juicy lamb shank, infused with fresh rosemary and sage, is a house specialty. Served with smooth mashed potatoes and char-grilled, crispy asparagus, topped with a tangy golden-brown glaze for a meal hard to forget.',
    },
    {
        id: 2,
        image: '/images/ciao.jpg',
        title: 'Ciao Ciao Gelato',
        address: 'Thao Dien, Q2',
        rating: '4.5 stars',
        description: 'Slow-cooked for eight hours, this intensely flavored and juicy lamb shank, infused with fresh rosemary and sage, is a house specialty. Served with smooth mashed potatoes and char-grilled, crispy asparagus, topped with a tangy golden-brown glaze for a meal hard to forget.',
    },
    {
        id: 3,
        image: '/images/nyb.jpg',
        title: 'New York Bagel',
        address: 'Thao Dien, Q2',
        rating: '4.5 stars',
        description: 'Slow-cooked for eight hours, this intensely flavored and juicy lamb shank, infused with fresh rosemary and sage, is a house specialty. Served with smooth mashed potatoes and char-grilled, crispy asparagus, topped with a tangy golden-brown glaze for a meal hard to forget.',
    },
    {
        id: 4,
        image: '/images/bg.png',
        title: 'Bun Bo',
        address: 'Thao Dien, Q2',
        rating: '4.5 stars',
        description: 'Slow-cooked for eight hours, this intensely flavored and juicy lamb shank, infused with fresh rosemary and sage, is a house specialty. Served with smooth mashed potatoes and char-grilled, crispy asparagus, topped with a tangy golden-brown glaze for a meal hard to forget.',
    },
    {
        id: 5,
        image: '/images/bg.png',
        title: 'Viet food',
        address: 'Thao Dien, Q2',
        rating: '4.5',
        description: 'Slow-cooked for eight hours, this intensely flavored and juicy lamb shank, infused with fresh rosemary and sage, is a house specialty. Served with smooth mashed potatoes and char-grilled, crispy asparagus, topped with a tangy golden-brown glaze for a meal hard to forget.',
    },
    {
        id: 6,
        image: '/images/bg.png',
        title: 'Bun Bo',
        address: 'Thao Dien, Q2',
        rating: '4.5',
        description: 'Slow-cooked for eight hours, this intensely flavored and juicy lamb shank, infused with fresh rosemary and sage, is a house specialty. Served with smooth mashed potatoes and char-grilled, crispy asparagus, topped with a tangy golden-brown glaze for a meal hard to forget.',
    },
    {
        id: 7,
        image: '/images/bg.png',
        title: 'Viet food',
        address: 'Thao Dien, Q2',
        rating: '4.5',
        description: 'Slow-cooked for eight hours, this intensely flavored and juicy lamb shank, infused with fresh rosemary and sage, is a house specialty. Served with smooth mashed potatoes and char-grilled, crispy asparagus, topped with a tangy golden-brown glaze for a meal hard to forget.',
    },
    {
        id: 8,
        image: '/images/bg.png',
        title: 'Bun Bo',
        address: 'Thao Dien, Q2',
        rating: '4.5',
        description: 'Slow-cooked for eight hours, this intensely flavored and juicy lamb shank, infused with fresh rosemary and sage, is a house specialty. Served with smooth mashed potatoes and char-grilled, crispy asparagus, topped with a tangy golden-brown glaze for a meal hard to forget.',
    },
]